server:
  port: 8080

zuul:
  routes:
    demo-one:
      path: /demo-one/**
      serviceId: demo-one
      stripPrefix: false

ribbon:
  eureka:
    enabled: false

demo-one:
  ribbon:
    listOfServers: 172.17.0.2:80,172.17.0.3:80

logging:
  path: /var/local/dingshuai/demo-zuul/logs